# Generated by Django 2.0.4 on 2018-04-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TitanicPeople',
            fields=[
                ('passengerid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('survived', models.BooleanField(default=False)),
                ('pclass', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('sex', models.CharField(blank=True, max_length=6, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('Sibsp', models.IntegerField(blank=True, null=True)),
                ('parch', models.IntegerField(blank=True, null=True)),
                ('ticket', models.CharField(blank=True, max_length=20, null=True)),
                ('fare', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('cabin', models.CharField(blank=True, max_length=20, null=True)),
                ('embarked', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
    ]
